### ISSUE TITLE
incorrect pinout on RP2040-Zero

### ISSUE THREAD

**Issue by vrz** [bill88t/ljinux#75]
Command pinout incorrectly shows pins on the backside of RP2040-Zero board.

| now | should be |
| --- | --- |
| GND | GND |
| GP1 | GP25 |
| GP2 | GP24 |
| GP3 | GP23 |
| GP4 | GP22 |
| GP5 | GP21 |
| GP6 | GP20 |
| GP7 | GP19 |
| GP8 | GP18 |
| | GP17 |

**Comment by vrz** [comment]
i've found some another mistakes in pinouts.
here are correct pinouts: https://www.waveshare.com/wiki/File:RP2040-Zero-details-7.jpg

**Comment by bill88t** [comment]
Thanks for spotting this!

I have created a PR fixing the pinout along with some neopixel code.
Should you have no more changes to propose, I will merge this PR in 4 hours.
Should you approve of the PR, I will merge it immediately.

(Direct pr link, in case you are viewing this from email: https://github.com/bill88t/ljinux/issues/75)
