### ISSUE TITLE
A common objective or a roadmap for the project.

### ISSUE THREAD

**Issue by mdaadoun** [bill88t/ljinux#9]
Hello,
I discovered your project from the recent article at hackster, I feel this idea of a linux toy for the pico is really fun and could go far as an open source project. I will try to help as I like to play with my rpi400 and pico and it looks like the perfect project to come aboard while I am student in software engineering.
If the project become more popular as it iterate and attract more peoples maybe it would be interesting to give some idea for a long term vision, even if it is a toy for developers to have fun (do you know the SerenityOS ?), it would be good to kind of have milestones.

I believe one milestone could be to achieve Ljinux be fully compatible on a complete rp2040+hardware machine like the PICOmputer or the PicoSystem. That would be the most fun journey ever. :)
Here for ref:
* [WORLD’S FIRST RP2040 QWERTY COMPUTER](https://hackaday.com/2021/05/28/worlds-first-rp2040-qwerty-computer/)
* [PICOmputer](https://hackaday.io/project/179854-picomputer)
* [PicoSystem](https://blog.adafruit.com/2021/10/22/the-circuitpython-stage-game-library-ported-to-the-pimoroni-picosystem-circuitpython-raspberrypipico-piday-raspberry_pi-deshipu/)

Of course, it is an idea for a long term project, there would be many fun steps to reach before to have a fully OS toy for the RP2040.

Cheers

**Comment by bill88t** [comment]
Milestones & the project vision is something I should have already defined. I'll get started with that immediately. Yea, this project can indeed be summed up into a "rp2040 os toy" and supporting multiple fixed hardware configurations is something needed. The code to support custom hardware configurations is partially in place already in the form of config.json.
Sure, it will get time to make all the pins allocate based on that, but we're getting there.
I will put more details onto the roadmap issue.

**Comment by bill88t** [comment]
#10 is now in place. If you feel like something more is needed, reopen this issue, or create a new one.
